AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Cognizant Cloud Acceleration Platform Generated AWS Lambda Function for test.demo

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Tracing: Active
  Api:
    TracingEnabled: True
Resources:
  CCAPDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Demo_table # table name must be given here
      PrimaryKey:  # Primary/Partition key details must be given here
        Name: demo
        Type: String
      ProvisionedThroughput:  # Provisioned throughput details must be given here
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  CCAPLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: test.demo
      Handler: com.testing.App::handleRequest
      Runtime: java8.al2
      MemorySize: 512
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref CCAPDynamoDBTable
      
      Events:
        CCAPAPI1:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /home/{/root/test}
            Method: get
Outputs:
  CCAPGeneratedAPI:
    Description: "API Gateway endpoint URL for Prod stage for CCAP Generated /home API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/home/{/root/test}"
  CCAPLambda:
    Description: "CCAP Generated Hello World Lambda Function ARN"
    Value: !GetAtt CCAPLambda.Arn
  CCAPLambdaIamRole:
    Description: "Implicit IAM Role created for CCAP Generated Hello World function"
    Value: !GetAtt CCAPLambdaRole.Arn
  
  
  CCAPDynamoDBTable:
    Description: "CCAP Generated Dynamodb Table Arn"
    Value: !GetAtt CCAPDynamoDBTable.Arn
